@startuml
participant "RobDroneGo UI" as UI
participant "RobDroneGo" as API

activate UI
activate API
UI -> API : 1 : .get(/x)
API -> API : 1.1 : get all x's from database
API --> UI : 2 : response status

@enduml
