@startuml lvl2
participant "RobDroneGo UI" as UI
participant "RobDroneGo MD" as API
database "mongoDB" as BD

activate UI
activate API
UI -> API : 1 : .put(/x)
API -> BD : 1.1 : .find(/x) in the database
activate BD

BD --> API : 1.2 : response status
deactivate BD

API -> API : 1.1 : updates the x

API -> BD :1.3 : .put(/x) update x on database
activate BD

BD --> API : 1.4 : response status
deactivate BD
API --> UI : 2 : success or failure

@enduml
