@startuml
participant "RobDroneGo UI" as UI
participant "RobDroneGo" as API

activate UI
activate API
UI -> API : 1 : .put(/x)
API -> API : 1.1 : updates the x \n and saves it to the database
API --> UI : 2 : response status

@enduml
