@startuml lvl1
actor "Client" as OE

activate OE
OE -> ":RobDroneGO" : 1 : starts edition process
activate ":RobDroneGO"
":RobDroneGO" --> OE : 1.1 : requests data of x
deactivate ":RobDroneGO"
OE -> ":RobDroneGO" : 2 : inserts the data of x
activate ":RobDroneGO"
":RobDroneGO" --> OE : 2.1 : success or failure


deactivate ":RobDroneGO"

@enduml
