@startuml lvl1
actor "Client" as OE

activate OE
OE -> ":RobDroneGO" : 1 : requests all x's
activate ":RobDroneGO"
":RobDroneGO" --> OE : 1.1 : return List with x's
deactivate ":RobDroneGO"



@enduml
